import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Aquí puedes incluir tus metadatos, estilos, scripts, etc. */}
      </head>
      <body className={inter.className} style={{ backgroundColor: 'white' }}>
        <header>
          {/* Aquí puedes colocar tu encabezado */}
          <img src="/R.png" alt="Descripción de la imagen" style={{ width: '300px', height: 'auto' }} />
        </header>
        {children}
        <footer>
          {/* Aquí puedes colocar tu pie de página */}
          <p>© 2024 Tu Empresa - Todos los derechos reservados</p>
        </footer>
      </body>
    </html>
  );
}
